'use client';
import { useEffect, useMemo, useState } from 'react';
import { supabase } from '@/lib/supabase';

type Category={id:string;name:string};
type Item={id:string;category_id:string|null;name:string;price:number;is_veg:boolean;is_available:boolean};
type Line={item:Item;quantity:number};

export default function POSPage(){
 const [branchId,setBranchId]=useState(''); const [categories,setCategories]=useState<Category[]>([]); const [items,setItems]=useState<Item[]>([]); const [category,setCategory]=useState('all'); const [cart,setCart]=useState<Line[]>([]); const [loading,setLoading]=useState(true); const [message,setMessage]=useState('');
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser(); if(!user)return; const {data:membership}=await supabase.from('branch_memberships').select('branch_id').eq('user_id',user.id).eq('is_active',true).limit(1).maybeSingle(); if(!membership)return setLoading(false); setBranchId(membership.branch_id); const [c,i]=await Promise.all([supabase.from('categories').select('id,name').eq('branch_id',membership.branch_id).eq('is_active',true).order('sort_order'),supabase.from('menu_items').select('id,category_id,name,price,is_veg,is_available').eq('branch_id',membership.branch_id).eq('is_active',true).eq('is_available',true).order('name')]); setCategories(c.data??[]); setItems(i.data??[]); setLoading(false);})();},[]);
 const visible=useMemo(()=>category==='all'?items:items.filter(i=>i.category_id===category),[items,category]); const total=cart.reduce((s,l)=>s+l.item.price*l.quantity,0);
 function add(item:Item){setCart(c=>{const x=c.find(l=>l.item.id===item.id);return x?c.map(l=>l.item.id===item.id?{...l,quantity:l.quantity+1}:l):[...c,{item,quantity:1}]})}
 async function placeOrder(){if(!branchId||!cart.length)return;setMessage('Creating order…'); const subtotal=total; const {data:{user}}=await supabase.auth.getUser(); const {data:order,error}=await supabase.from('orders').insert({branch_id:branchId,order_type:'QUICK_BILL',status:'OPEN',subtotal,tax_amount:0,grand_total:subtotal,created_by:user?.id}).select('id').single(); if(error||!order){setMessage(error?.message??'Unable to create order');return} const {error:itemError}=await supabase.from('order_items').insert(cart.map(l=>({order_id:order.id,menu_item_id:l.item.id,item_name:l.item.name,quantity:l.quantity,unit_price:l.item.price,line_total:l.item.price*l.quantity,kitchen_status:'NEW'}))); if(itemError){setMessage(itemError.message);return} setCart([]);setMessage('Order created and sent to KOT queue.');}
 if(loading)return <main className="grid min-h-screen place-items-center">Loading POS…</main>;
 return <main className="min-h-screen bg-slate-50 p-4 lg:p-6"><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-[1fr_360px]"><section><div className="mb-4 flex flex-wrap gap-2"><button onClick={()=>setCategory('all')} className={`rounded-full px-4 py-2 text-sm font-semibold ${category==='all'?'bg-slate-900 text-white':'bg-white'}`}>All</button>{categories.map(c=><button key={c.id} onClick={()=>setCategory(c.id)} className={`rounded-full px-4 py-2 text-sm font-semibold ${category===c.id?'bg-slate-900 text-white':'bg-white'}`}>{c.name}</button>)}</div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{visible.map(i=><button key={i.id} onClick={()=>add(i)} className="rounded-2xl bg-white p-4 text-left shadow-sm ring-1 ring-slate-100 hover:ring-slate-300"><div className="flex justify-between gap-3"><span className="font-bold">{i.name}</span><span className="font-semibold">₹{Number(i.price).toFixed(2)}</span></div><span className="mt-2 inline-block text-xs text-slate-500">{i.is_veg?'VEG':'NON-VEG'}</span></button>)}</div></section><aside className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-100"><h1 className="text-xl font-bold">Current Bill</h1><div className="mt-4 space-y-3">{cart.length===0?<p className="text-sm text-slate-400">Tap menu items to add.</p>:cart.map(l=><div key={l.item.id} className="flex justify-between gap-3 text-sm"><span>{l.item.name} × {l.quantity}</span><span>₹{(l.item.price*l.quantity).toFixed(2)}</span></div>)}</div><div className="mt-5 border-t pt-4 flex justify-between text-lg font-bold"><span>Total</span><span>₹{total.toFixed(2)}</span></div><button disabled={!cart.length} onClick={placeOrder} className="mt-4 w-full rounded-xl bg-slate-900 px-4 py-3 font-semibold text-white disabled:opacity-40">Create KOT / Order</button>{message&&<p className="mt-3 rounded-xl bg-slate-100 p-3 text-sm">{message}</p>}</aside></div></main>;
}