import { Router } from 'express';
import { z } from 'zod';
import { requireAuth } from '../middleware/auth.js';
import { requireBranch, type BranchRequest } from '../middleware/branch.js';
import { createUserClient } from '../lib/supabase.js';

export const inventoryRouter=Router();
inventoryRouter.use(requireAuth,requireBranch);
const itemSchema=z.object({name:z.string().trim().min(1).max(120),sku:z.string().trim().max(60).optional().nullable(),unit:z.string().trim().min(1).max(20),minimum_stock:z.number().min(0).default(0),cost_per_unit:z.number().min(0).default(0),is_active:z.boolean().default(true)});
const recipeSchema=z.object({menu_item_id:z.string().uuid(),name:z.string().trim().max(120).optional().nullable(),yield_quantity:z.number().positive(),ingredients:z.array(z.object({inventory_item_id:z.string().uuid(),quantity:z.number().positive()})).default([])});
const supplierSchema=z.object({name:z.string().trim().min(1).max(160),phone:z.string().trim().max(30).optional().nullable(),email:z.string().email().optional().nullable(),address:z.string().trim().max(500).optional().nullable(),gstin:z.string().trim().max(30).optional().nullable(),opening_balance:z.number().default(0)});
const purchaseSchema=z.object({supplier_id:z.string().uuid().optional().nullable(),invoice_number:z.string().trim().max(100).optional().nullable(),purchase_date:z.string(),tax_amount:z.number().min(0).default(0),payment_status:z.string().default('PENDING'),paid_amount:z.number().min(0).default(0),notes:z.string().max(1000).optional().nullable(),items:z.array(z.object({inventory_item_id:z.string().uuid(),quantity:z.number().positive(),unit_cost:z.number().min(0),tax_amount:z.number().min(0).default(0)})).min(1),idempotency_key:z.string().max(100).optional()});
async function client(r:BranchRequest){return createUserClient(r.accessToken)}
async function manager(r:BranchRequest){const s=await client(r);const {data}=await s.from('branch_memberships').select('role').eq('branch_id',r.branchId).eq('user_id',r.user.id).eq('is_active',true).maybeSingle();return !!data&&['OWNER','ADMIN','MANAGER','INVENTORY_MANAGER'].includes(data.role)}
inventoryRouter.get('/items',async(req,res,next)=>{try{const r=req as BranchRequest,s=await client(r);const {data,error}=await s.from('inventory_items').select('*').eq('branch_id',r.branchId).order('name');if(error)throw error;res.json({success:true,data})}catch(e){next(e)}});
inventoryRouter.get('/low-stock',async(req,res,next)=>{try{const r=req as BranchRequest,s=await client(r);const {data,error}=await s.from('inventory_items').select('*').eq('branch_id',r.branchId).eq('is_active',true).filter('current_stock','lte','minimum_stock').order('name');if(error)throw error;res.json({success:true,data})}catch(e){next(e)}});
inventoryRouter.post('/items',async(req,res,next)=>{try{const r=req as BranchRequest;if(!(await manager(r)))return res.status(403).json({success:false,message:'Inventory manager permission required'});const b=itemSchema.parse(req.body),s=await client(r);const {data,error}=await s.from('inventory_items').insert({...b,branch_id:r.branchId,current_stock:0}).select('*').single();if(error)throw error;res.status(201).json({success:true,data})}catch(e){next(e)}});
inventoryRouter.post('/adjust',async(req,res,next)=>{try{const r=req as BranchRequest;if(!(await manager(r)))return res.status(403).json({success:false,message:'Inventory manager permission required'});const b=z.object({inventory_item_id:z.string().uuid(),quantity:z.number().refine(n=>n!==0),movement_type:z.string(),notes:z.string().max(500).optional()}).parse(req.body),s=await client(r);const {data,error}=await s.rpc('adjust_inventory_stock',{p_branch_id:r.branchId,p_inventory_item_id:b.inventory_item_id,p_quantity:b.quantity,p_movement_type:b.movement_type,p_notes:b.notes??null,p_created_by:r.user.id});if(error)throw error;res.json({success:true,data})}catch(e){next(e)}});
inventoryRouter.get('/movements/:itemId',async(req,res,next)=>{try{const r=req as BranchRequest,s=await client(r);const id=z.string().uuid().parse(req.params.itemId);const {data,error}=await s.from('stock_movements').select('*').eq('branch_id',r.branchId).eq('inventory_item_id',id).order('created_at',{ascending:false}).limit(200);if(error)throw error;res.json({success:true,data})}catch(e){next(e)}});
inventoryRouter.get('/recipes',async(req,res,next)=>{try{const r=req as BranchRequest,s=await client(r);const {data,error}=await s.from('recipes').select('*,recipe_ingredients(*,inventory_items(id,name,unit))').eq('branch_id',r.branchId).order('name');if(error)throw error;res.json({success:true,data})}catch(e){next(e)}});
inventoryRouter.post('/recipes',async(req,res,next)=>{try{const r=req as BranchRequest;if(!(await manager(r)))return res.status(403).json({success:false,message:'Manager permission required'});const b=recipeSchema.parse(req.body),s=await client(r);const {ingredients,...recipe}=b;const {data,error}=await s.from('recipes').upsert({...recipe,branch_id:r.branchId},{onConflict:'branch_id,menu_item_id'}).select('*').single();if(error)throw error;await s.from('recipe_ingredients').delete().eq('recipe_id',data.id);if(ingredients.length){const {error:e}=await s.from('recipe_ingredients').insert(ingredients.map(x=>({...x,recipe_id:data.id})));if(e)throw e}res.status(201).json({success:true,data})}catch(e){next(e)}});
inventoryRouter.get('/suppliers',async(req,res,next)=>{try{const r=req as BranchRequest,s=await client(r);const {data,error}=await s.from('suppliers').select('*').eq('branch_id',r.branchId).order('name');if(error)throw error;res.json({success:true,data})}catch(e){next(e)}});
inventoryRouter.post('/suppliers',async(req,res,next)=>{try{const r=req as BranchRequest;if(!(await manager(r)))return res.status(403).json({success:false,message:'Manager permission required'});const s=await client(r),b=supplierSchema.parse(req.body),{data,error}=await s.from('suppliers').insert({...b,branch_id:r.branchId}).select('*').single();if(error)throw error;res.status(201).json({success:true,data})}catch(e){next(e)}});
inventoryRouter.get('/purchases',async(req,res,next)=>{try{const r=req as BranchRequest,s=await client(r);const {data,error}=await s.from('purchases').select('*,suppliers(id,name),purchase_items(*)').eq('branch_id',r.branchId).order('purchase_date',{ascending:false}).limit(100);if(error)throw error;res.json({success:true,data})}catch(e){next(e)}});
inventoryRouter.post('/purchases',async(req,res,next)=>{try{const r=req as BranchRequest;if(!(await manager(r)))return res.status(403).json({success:false,message:'Manager permission required'});const b=purchaseSchema.parse(req.body),s=await client(r),subtotal=b.items.reduce((n,x)=>n+x.quantity*x.unit_cost,0),total=subtotal+b.tax_amount;const {data:p,error}=await s.from('purchases').insert({branch_id:r.branchId,supplier_id:b.supplier_id??null,invoice_number:b.invoice_number??null,purchase_date:b.purchase_date,subtotal,tax_amount:b.tax_amount,total_amount:total,payment_status:b.payment_status,paid_amount:b.paid_amount,notes:b.notes??null,created_by:r.user.id,idempotency_key:b.idempotency_key??null}).select('*').single();if(error)throw error;const {error:ie}=await s.from('purchase_items').insert(b.items.map(x=>({...x,purchase_id:p.id,total_amount:x.quantity*x.unit_cost+x.tax_amount})));if(ie)throw ie;res.status(201).json({success:true,data:p})}catch(e){next(e)}});
inventoryRouter.post('/purchases/:id/receive',async(req,res,next)=>{try{const r=req as BranchRequest;if(!(await manager(r)))return res.status(403).json({success:false,message:'Manager permission required'});const id=z.string().uuid().parse(req.params.id),s=await client(r),{data,error}=await s.rpc('receive_purchase',{p_purchase_id:id,p_branch_id:r.branchId,p_user_id:r.user.id});if(error)throw error;res.json({success:true,data})}catch(e){next(e)}});
inventoryRouter.post('/orders/:id/consume-stock',async(req,res,next)=>{try{const r=req as BranchRequest;if(!(await manager(r)))return res.status(403).json({success:false,message:'Manager permission required'});const id=z.string().uuid().parse(req.params.id),s=await client(r),{data,error}=await s.rpc('consume_order_stock',{p_order_id:id,p_branch_id:r.branchId,p_user_id:r.user.id});if(error)throw error;res.json({success:true,data:{movements:data}})}catch(e){next(e)}});
